#!/usr/bin/with-contenv bash
# shellcheck shell=bash

WEBUI_PORT=${WEBUI_PORT:-8080}
if [[ -n "${TORRENTING_PORT}" ]]; then
    TORRENTING_PORT_ARG="--torrenting-port=${TORRENTING_PORT}"
fi

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost ${WEBUI_PORT}" \
        s6-setuidgid abc /usr/bin/qbittorrent-nox --webui-port="${WEBUI_PORT}" ${TORRENTING_PORT_ARG}
