#!/usr/bin/with-contenv bash
# shellcheck shell=bash

WEBUI_PORT=${WEBUI_PORT:-8080}
TORRENTING_PORT=${TORRENTING_PORT:-6881}

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost ${WEBUI_PORT}" \
        s6-setuidgid abc /app/qbittorrent-nox --webui-port="${WEBUI_PORT}" --torrenting-port="${TORRENTING_PORT}"
