name: Mark stale issues and pull requests
on:
  schedule:
    - cron:  '29 15 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  stale:
    permissions:
      issues: write
      pull-requests: write
    uses: linuxserver/github-workflows/.github/workflows/issues-cron.yml@v1
    secrets: inherit
