#!/usr/bin/with-contenv bash

# make our folder
mkdir -p /config/qBittorrent

# copy config
if [[ ! -e /config/qBittorrent/qBittorrent.conf ]]; then
  cp /defaults/qBittorrent.conf /config/qBittorrent/qBittorrent.conf
fi

# v4.3.3 BT_backup migration
if [[ -d /config/data/qBittorrent/BT_backup/ ]]; then
  mv /config/qBittorrent/BT_backup/ /config/qBittorrent/BT_backup.bak/ && \
    mkdir /config/qBittorrent/BT_backup/ && \
    cp -a /config/data/qBittorrent/BT_backup/.  /config/qBittorrent/BT_backup/ && \
    mv /config/data/qBittorrent/BT_backup/ /config/data/qBittorrent/BT_backup.old/
fi

# chown download directory if currently not set to abc
if [[ -d /downloads ]]; then
  if [[ "$(stat -c '%U' /downloads)" != "abc" ]]; then
    chown -R abc:abc /downloads
  fi
fi

# permissions
chown -R abc:abc \
	/config
